import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Skills from "./skills";
import animation from "../styles/animation.module.scss";
import { createRef, MouseEvent, useEffect, useRef, useState } from "react";
import { rubberband, runRubberbandIn } from "../utils/animation";
import Projects from "./projects";
import Contact from "./contact";
import { motion, useInView } from "framer-motion";
import Navbar from "../components/Navbar";
import About from "./about";
import PageTitle from "../components/PageTitle";
import Landing from "./landing";
import {
  Button,
  Drawer,
  DrawerBody,
  DrawerCloseButton,
  DrawerContent,
  DrawerHeader,
  DrawerOverlay,
  Flex,
  Grid,
  GridItem,
} from "@chakra-ui/react";
import { HamburgerIcon, CloseIcon } from "@chakra-ui/icons";
import DecorativeTag from "../components/DecorativeTag";
import { FadeInContainer } from "../components/FadeInTransition";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Shawn Su's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        h="100%"
        templateRows="repeat(1, 1fr)"
        templateColumns="repeat(20, 1fr)"
        gap={0}
      >
        {/* only shown on md or beyond */}
        <GridItem
          display={{ base: "none", md: "block" }}
          w="8rem"
          rowSpan={10}
          colSpan={1}
          bg="gray"
        >
          {/* use default buttonPadding value here */}
          <Navbar />
        </GridItem>

        {/* only shown on base & sm */}
        <GridItem
          display={{ base: "inline-block", md: "none" }}
          w="4rem"
          h="4rem"
          position="fixed"
          right="1rem"
        >
          <Button
            w="4rem"
            h="4rem"
            top="0.5rem"
            bg="none"
            _hover={{ bg: "none" }}
            _active={{ bg: "none", opacity: "0.7" }}
            onClick={() => setIsOpen((prev) => !prev)}
          >
            {isOpen ? null : (
              // (
              //   <CloseIcon boxSize="2.8rem" />
              // )
              <HamburgerIcon boxSize={{ base: "3rem", sm: "4rem" }} />
            )}
          </Button>
        </GridItem>

        <Drawer
          placement="bottom"
          onClose={() => setIsOpen(false)}
          isOpen={isOpen}
        >
          <DrawerOverlay />
          <DrawerContent>
            <DrawerCloseButton />
            <DrawerBody>
              <Navbar
                buttonPadding="1rem 50vw"
                onClick={() => setIsOpen(false)}
              />
            </DrawerBody>
          </DrawerContent>
        </Drawer>

        {/* Home Page */}
        <GridItem colSpan={19} bg="mintcream">
          <DecorativeTag content="html" hExpand="-0.5rem">
            <DecorativeTag content="body" hExpand="-1rem">
              <Flex flexDirection={"column"}>
                <Landing />
                <About />
                <Projects />
                <Skills />
                <Contact />
              </Flex>
            </DecorativeTag>
          </DecorativeTag>
        </GridItem>
      </Grid>
    </div>
  );
};

export default Home;
